site_name: Ch3ckm8 Vault
site_author: 'ch3ckm8'

docs_dir: docs/

site_url: https://ch3ckm8.github.io/personal_blog4/
use_directory_urls: true

nav:
  - Welcome: index.md
  - HTB Writeups:
      - Active: ch3ckm8_HTB_Active.md
      - Administrator: ch3ckm8_HTB_Administrator.md
      - Blackfield: ch3ckm8_HTB_Blackfield.md
      - Cascade: ch3ckm8_HTB_Cascade.md
      - EscapeTwo: ch3ckm8_HTB_EscapeTwo.md
      - Nocturnal: ch3ckm8_HTB_Nocturnal.md
      - Return: ch3ckm8_HTB_Return.md
      - TheFrizz: ch3ckm8_HTB_TheFrizz.md
      - Forest: ch3ckm8_HTB_forest.md
      - Monteverde: ch3ckm8_HTB_monteverde.md
      - Sauna: ch3ckm8_HTB_sauna.md
      - Timelapse: ch3ckm8_HTB_Timelapse.md
      - Cicada: ch3ckm8_HTB_cicada.md
      - Escape: ch3ckm8_HTB_Escape.md
      - Flight: ch3ckm8_HTB_Flight.md
      - Fluffy: ch3ckm8_HTB_fluffy.md
      - Puppy: ch3ckm8_HTB_puppy.md
      - Tombwatcher: ch3ckm8_HTB_tombwatcher.md
      - Certified: ch3ckm8_HTB_certified.md
  - Other CTF Writeups:
      - RoboGRoot's-Portfolio: ch3ckm8_RoboGRoot-CTF_Portfolio.md
  - Notes:
      - Commonly used tools and methodologies: common_tools.md
      

theme:
  name: material
  highlightjs: true
  highlightjs_style: vs
  # Disable permalinks for headers
  header_autolink: false

  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - toc.sticky
    - toc.follow        # ðŸ‘ˆ auto-scrolls TOC outline
    - content.code.copy
    - navigation.top
    - navigation.external

  icon:
    logo: material/chess-knight
    repo: material/github

markdown_extensions:
  - attr_list
  - nl2br
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
            
extra:
  links:
    external_new_tab: true
  favicon: assets/images/chess-knight.svg


extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js
  - assets/javascripts/obsidian_tags.js

extra_css:
  - assets/stylesheets/interactive_graph.css
  - assets/stylesheets/obsidian_tags.css
  - assets/stylesheets/custom.css

plugins:
  - obsidian-interactive-graph:
      include_wikilinks: true
      include_markdown_links: true
  - search
  - tags:
     tags_file: tags.md
